---
- name: Enable Azure Arc Extensions
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - arc_hosts is defined
          - resource_group is defined
          - region is defined
          - extension is defined
        fail_msg: "Required variables not set"

    - name: Ensure that the az CLI has logged in with a service principal
      ansible.builtin.command: "az login --service-principal -u {{ lookup('env', 'AZURE_CLIENT_ID') }} -p {{ lookup('env', 'AZURE_SECRET') }} --tenant {{ lookup('env', 'AZURE_TENANT') }}"
      register: sp_login
      changed_when: sp_login.rc != 0

    - name: Enable Azure Monitor on Linux
      ansible.builtin.import_role:
        name: arc
        tasks_from: enable_arc_extension
      vars:
        name: "{{ extensions.azure_monitor_agent.name }}"
        type: "{{ extensions.azure_monitor_agent.type }}"
        publisher: "{{ extensions.azure_monitor_agent.publisher }}"
      when: extension == "azure_monitor_agent"

    - name: Enable Azure Log Analytics on Linux
      ansible.builtin.import_role:
        name: arc
        tasks_from: enable_arc_extension
      vars:
        name: "{{ extensions.log_analytics_agent.name }}"
        type: "{{ extensions.log_analytics_agent.type }}"
        publisher: "{{ extensions.log_analytics_agent.publisher }}"
      when: extension == "log_analytics_agent"

    - name: Enable AD SSH Login on Linux
      ansible.builtin.import_role:
        name: arc
        tasks_from: enable_arc_extension
      vars:
        name: "{{ extensions.ad_ssh_login.name }}"
        type: "{{ extensions.ad_ssh_login.type }}"
        publisher: "{{ extensions.ad_ssh_login.publisher }}"
      when: extension == "ad_ssh_login"

    - name: Enable Microsoft Defender on Linux
      ansible.builtin.import_role:
        name: arc
        tasks_from: enable_arc_extension
      vars:
        name: "{{ extensions.microsoft_defender.name }}"
        type: "{{ extensions.microsoft_defender.type }}"
        publisher: "{{ extensions.microsoft_defender.publisher }}"
      when: extension == "microsoft_defender"
