---
- name: Delete Windows Demo VM
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - azure.azcollection
  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - resource_group is defined
        fail_msg: "Required variables not set"

    - name: Delete Windows VMs
      ansible.builtin.import_role:
        name: vms
        tasks_from: delete_windows_vm
