---
- name: Create RHEL Demo VM
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - azure.azcollection
  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - region is defined
          - resource_group_name is defined
          - nic_name is defined
          - network_sec_group_name is defined
          - public_ip_name is defined
          - vnet_name is defined
          - subnet_name is defined
          - create_public_ip is defined
          - vm_name is defined
          - ssh_public_key is defined
        fail_msg: "Required variables not set"

    - name: Create a RHEL VM
      ansible.builtin.import_role:
        name: vms
        tasks_from: create_rhel_vm
