---
- name: Ensure gdb is installed
  ansible.builtin.dnf:
    name: gdb
    state: latest

- name: Download Agent on Linux Machines
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh
    dest: /tmp/onboard_agent.sh
    mode: '0755'

- name: Install Agent on Linux Machines
  ansible.builtin.command: "sh /tmp/onboard_agent.sh -w {{ analytics_workspace.customer_id }} -s {{ analytics_workspace.shared_keys.primary_shared_key }}"
