---
- name: Set extension.use_dynamic_install to yes_without_prompt
  ansible.builtin.command: az config set extension.use_dynamic_install=yes_without_prompt

- name: Disable the log analytics extension on Arc connected devices
  ansible.builtin.command: az connectedmachine extension delete --machine-name "{{ item }}" --name "{{ extensions.log_analytics_agent.name }}" --resource-group "{{ resource_group_name }}" --no-wait --yes
  loop: "{{ hosts }}"
