---
- name: Disable extensions on Arc connected devices
  ansible.builtin.shell: |
    az connectedmachine extension delete \
    --machine-name "{{ item.0 }}" \
    --name "{{ item.1 }}" \
    --resource-group "{{ resource_group }}" \
    --no-wait \
    --yes
  loop: "{{ arc_hosts | product(extension_names) | list }}"
  register: sp_login
  changed_when: sp_login.rc != 0
