---
- name: Get extension.use_dynamic_install setting
  ansible.builtin.command: az config get extension.use_dynamic_install
  register: use_dynamic_install_results
  changed_when: false

- name: Set extension.use_dynamic_install to true
  ansible.builtin.command: az config set extension.use_dynamic_install=yes_without_prompt
  when: >
    ("yes_without_prompt" not in use_dynamic_install_results.stdout)

- name: Disable the log analytics extension on Arc connected devices
  ansible.builtin.command: az connectedmachine extension delete --machine-name "{{ item }}" --name "{{ extensions.log_analytics_agent.name }}" --resource-group "{{ resource_group_name }}" --no-wait --yes
  loop: "{{ hosts }}"
