---
- name: Enable the log analytics extension on Arc connected devices
  ansible.builtin.command: az connectedmachine extension create --machine-name "{{ item }}" --name "{{ extensions.log_analytics_agent.name }}" --location "{{ region }}" --settings "{\"workspaceId\":\"{{ analytics_workspace.customer_id }}\"}" --protected-settings "{\"workspaceKey\":\"{{ analytics_workspace.shared_keys.primary_shared_key }}\"}" --resource-group "{{ resource_group_name }}" --type-handler-version "{{ extensions.log_analytics_agent.type_handler_version }}" --type "{{ extensions.log_analytics_agent.type }}" --publisher "{{ extensions.log_analytics_agent.publisher }}" --enable-auto-upgrade true --auto-upgrade-minor true --no-wait
  loop: "{{ hosts }}"
  register: create_extension_results
  failed_when: >
    ("Error" in create_extension_results.stdout) and
    ("is still processing" not in create_extension_results.stdout)
