---
- name: Enable Azure Arc Extension
  ansible.builtin.shell: |
    az connectedmachine extension create \
    --machine-name "{{ item }}" \
    --name "{{ name }}" \
    --location "{{ region }}" \
    --resource-group "{{ resource_group }}" \
    --type "{{ type }}" \
    --publisher "{{ publisher }}" \
    --enable-auto-upgrade true \
    --auto-upgrade-minor true \
    --no-wait
  loop: "{{ arc_hosts }}"
  register: results
  changed_when: results.rc != 0
  failed_when: ("ERROR" in results.stderr)

- name: Debug Enablement
  ansible.builtin.debug:
    var: results

- name: Register Enablement
  ansible.builtin.set_stats:
    data:
      arc_enablement_results: results
