---
- name: Get Demo VM by tags
  azure.azcollection.azure_rm_virtualmachine_info:
    resource_group: "{{ resource_group }}"
    tags:
      - ansible-collection:azure.infrastructure_config_demos
      - ansible-role:vms
      - ansible-task:create_windows_vm
  register: vm_results

- name: Delete VM
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_results.vms[0].name }}"
    state: absent
  when:
    - vm_results.vms is defined
    - vm_results.vms | length == 1

- name: Get Security Group by tags
  azure.azcollection.azure_rm_securitygroup_info:
    resource_group: "{{ resource_group }}"
    tags:
      - ansible-collection:azure.infrastructure_config_demos
      - ansible-role:vms
      - ansible-task:create_windows_vm
  register: sg_results

- name: Delete Security Group
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ sg_results.securitygroups[0].name }}"
    state: absent
  when:
    - sg_results.securitygroups is defined
    - sg_results.securitygroups | length == 1
