---
- name: Check operation validation
  ansible.builtin.fail:
    msg: "Please provide operation as 'create' or 'delete'"
  when: operation not in ['create', 'delete']

- name: Include operation tasks
  ansible.builtin.include_tasks: "{{ operation }}.yml"
