---
- name: Check if the Log Analytics Agent has already been installed on Linux servers
  ansible.builtin.stat:
    path: /opt/microsoft/omsagent
    get_attributes: false
    get_checksum: false
  register: log_agent_exists
  when: ansible_system == 'Linux'

- name: Download Agent on Linux Machines
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh
    dest: /tmp/onboard_agent.sh
    mode: '0755'
  when: ansible_system == 'Linux' and not log_agent_exists.stat.exists

- name: Install Agent on Linux Machines
  ansible.builtin.command: "sh /tmp/onboard_agent.sh -w {{ analytics_workspace.customer_id }} -s {{ analytics_workspace.shared_keys.primary_shared_key }}"
  when: ansible_system == 'Linux' and not log_agent_exists.stat.exists
