---
- name: Check if the Log Analytics Agent is installed on Linux servers
  ansible.builtin.stat:
    path: /opt/microsoft/omsagent/bin/uninstall
    get_attributes: false
    get_checksum: false
  register: log_agent_exists
  when: ansible_system == 'Linux'

- name: Uninstall Agent on Linux servers
  ansible.builtin.command: "sh /opt/microsoft/omsagent/bin/uninstall"
  register: uninstall_cmd
  when: ansible_system == 'Linux' and log_agent_exists.stat.exists
  failed_when: uninstall_cmd.rc == 1
  changed_when: uninstall_cmd.rc != 1

- name: Uninstall Agent on Windows servers
  block:
    - name: Get product id for the Log Analytics Agent on Windows servers
      ansible.windows.win_shell: 'Get-WmiObject Win32_Product | Where-Object {$_.Name -contains "Microsoft Monitoring Agent"} | Select-Object -ExpandProperty IdentifyingNumber'
      register: "{{ log_agent_product_id }}"

    - name: Uninstall all old Agents on Windows servers
      ansible.windows.win_package:
        product_id: '{{ item }}'
        state: absent
      loop: "{{ log_agent_product_id.stdout_lines }}"
      when: log_agent_product_id is defined and log_agent_product_id | length > 0
  when: ansible_os_family == 'Windows'