---
- name: Delete RHEL Demo VM
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - azure.azcollection
  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - resource_group_name is defined
        fail_msg: "Required variables not set"

    - name: Get Demo VM by tags
      azure_rm_virtualmachine_info:
        resource_group: "{{ resource_group_name }}"
        tags:
          - ansible-collection:lab.azure_roles
          - ansible-playbook:create_rhel_vm
      register: vm_results

    - name: Verify that VM was found
      ansible.builtin.assert:
        that:
          - vm_results.vms is defined
          - vm_results.vms | length == 1
        fail_msg: "VM count returned not equal to 1"
        success_msg: "Found 1 VM to delete"

    - name: Delete VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_results.vms[0].name }}"
        state: absent
