---
- name: Destroy hub and spoke network with virtual network gateway
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - azure.azcollection
  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - region is defined
          - resource_group_name is defined
        fail_msg: "Required variables not set"

    - name: Delete Transit Networking Model
      ansible.builtin.import_role:
        name: roles/transit_peered_networks
      vars:
        operation: delete
