---
- name: Replace Log Analytics Agent with Azure Agent
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - azure.azcollection
  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - linux_hosts is defined
          - resource_group_name is defined
        fail_msg: "Required variables not set"

    - name: Ensure that the az CLI has logged in with a service principal
      ansible.builtin.command: "az login --service-principal -u {{ lookup('env', 'AZURE_CLIENT_ID') }} -p {{ lookup('env', 'AZURE_SECRET') }} --tenant {{ lookup('env', 'AZURE_TENANT') }}"

    - name: Set extension.use_dynamic_install to yes_without_prompt
      ansible.builtin.command: az config set extension.use_dynamic_install=yes_without_prompt

    - name: Ensure that the az connectedmachine extension is installed
      ansible.builtin.command: az extension add --name connectedmachine -y

    - name: Enable Arc Azure Monitor Agent Extension on Linux Hosts
      ansible.builtin.import_role:
        name: roles/arc
        tasks_from: enable_azure_monitor_agent_extension
      vars:
        hosts: "{{ linux_hosts }}"

    - name: Disable Arc Log Analytics Extension on Linux Hosts
      ansible.builtin.import_role:
        name: roles/arc
        tasks_from: disable_extensions
      vars:
        hosts: "{{ linux_hosts }}"
        extension_names:
          - "{{ extensions.log_analytics_agent.name }}"

    # TODO: Add for Windows Hosts
